apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4317
  selector:
    app: opentelemetry-collector