apiVersion: v1
kind: ConfigMap
metadata:
  name: my-opentelemetry-collector
  namespace: default
  annotations:
    meta.helm.sh/release-name: my-opentelemetry-collector
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/component: standalone-collector
    app.kubernetes.io/instance: my-opentelemetry-collector
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.120.0
    helm.sh/chart: opentelemetry-collector-0.117.0
data:
  otel-collector-config.yaml: |
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${env:MY_POD_IP}:6831
          thrift_http:
            endpoint: ${env:MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${env:MY_POD_IP}:8888
      zipkin:
        endpoint: ${env:MY_POD_IP}:9411
      filelog:
        include: ["/var/log/nginx/access.log", "/var/log/nginx/error.log"]
        start_at: beginning
        operators:
          - type: regex_parser
            regex: '^(?P<timestamp>[^ ]*) (?P<remote_addr>[^ ]*) (?P<remote_user>[^ ]*) (?P<request_time>[^ ]*) (?P<request_method>[^ ]*) (?P<request_uri>[^ ]*) (?P<status>[^ ]*) (?P<body_bytes_sent>[^ ]*) (?P<http_referer>[^ ]*) (?P<http_user_agent>[^ ]*) (?P<http_x_forwarded_for>[^ ]*)$'
            timestamp:
              parse_from: timestamp
              layout: '%Y-%m-%dT%H:%M:%S.%fZ'
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    exporters:
      debug: {}
      coralogix:
        private_key: "<YOUR_CORALOGIX_PRIVATE_KEY>"
        application_name: "KubePOC"
        subsystem_name: "Nginx"
        endpoint: "https://api.coralogix.com/api/v1/logs"
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133
    service:
      extensions: [health_check]
      pipelines:
        logs:
          receivers: [otlp, filelog]
          processors: [memory_limiter, batch]
          exporters: [debug, coralogix]
        metrics:
          receivers: [otlp, prometheus]
          processors: [memory_limiter, batch]
          exporters: [debug]
        traces:
          receivers: [otlp, jaeger, zipkin]
          processors: [memory_limiter, batch]
          exporters: [debug]
      telemetry:
        metrics:
          address: ${env:MY_POD_IP}:8888