replicaCount: 1
image:
  repository: otel/opentelemetry-collector
  tag: "0.29.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 4317
config: |
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  processors:
    batch:
  exporters:
    logging:
    coralogix:
      private_key: "<YOUR_CORALOGIX_API_KEY>"
      application_name: "KubePOC"
      subsystem_name: "Nginx"
      endpoint: "https://api.coralogix.com/api/v1/logs"
    splunk_hec:
      token: "<YOUR_SPLUNK_HEC_TOKEN>"
      endpoint: "https://splunk.example.com:8088"
      source: "kubernetes"
      sourcetype: "_json"
  service:
    pipelines:
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging, coralogix, splunk_hec]
resources: {}