apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
  selector:
    app: elasticsearch

---

apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  ports:
    - port: {{ .Values.logstash.service.port }}
  selector:
    app: logstash

---

apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - port: {{ .Values.kibana.service.port }}
  selector:
    app: kibana